windowrule = opacity 0.80 override 0.80, match:class ^(Alacritty)$
windowrule = opacity 0.80 override 0.80, match:class ^(Code)$
windowrule = opacity 0.80 override 0.80, match:class ^(kitty)$
windowrule = opacity 0.80 override 0.80, match:class ^(thunar)$
windowrule = opacity 0.80 override 0.80, match:class ^(obsidian)$
windowrule = opacity 0.80 override 0.80, match:class ^(spotify)$
windowrule = opacity 0.80 override 0.80, match:class ^(discord)$
windowrule = opacity 0.80 override 0.80, match:class ^(vesktop)$
windowrule = opacity 0.80 override 0.80, match:class ^(org.telegram.desktop)$
windowrule = opacity 0.80 override 0.80, match:class ^(com.ayugram.desktop)$
windowrule = opacity 0.80 override 0.80, match:class ^(steam)$
windowrule = opacity 0.80 override 0.80, match:class ^(Rofi)$
windowrule = opacity 0.80 override 0.80, match:class ^(swaync)$
windowrule = opacity 0.80 override 0.80, match:class ^(better_control.py)$
