[general]
import = ["~/.config/alacritty/dracula.toml"]
live_config_reload = true
ipc_socket = true

[window]
decorations = "None"
opacity = 0.8

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font]
size = 10.0

[cursor]
style = "block"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"
