# COLORS
$bg = 111111
$bg2 = 1a1a1a
$surface = 222222
$border_active = aaaaaa
$border_inactive = 333333
$text = dddddd

general {
    gaps_in = 2
    gaps_out = 0
    border_size = 0

    col.active_border = rgb($border_active)
    col.inactive_border = rgb($border_inactive)

    layout = dwindle
}