# =========================
# CORE CONFIG FILES
# =========================

source = ~/.config/hypr/settings/monitors.conf
source = ~/.config/hypr/settings/general.conf
source = ~/.config/hypr/settings/env.conf
source = ~/.config/hypr/settings/rules.conf
source = ~/.config/hypr/settings/programs.conf
source = ~/.config/hypr/settings/autostart.conf

# =========================
# KEYBINDS
# =========================

source = ~/.config/hypr/keybinds/keybinds.conf
source = ~/.config/hypr/keybinds/input.conf

# =========================
# THEME / DECORATION
# =========================

source = ~/.config/hypr/themes/decoration.conf

# =========================
# ANIMATIONS
# =========================

source = ~/.config/hypr/animations.conf
source = /home/renks/.config/hypr/animations/BlackNode-Eclipse.conf
